version: "3.8"
services:
  db:
    image: postgres:14-alpine
    networks:
      - web
    env_file:
      - .env
    volumes:
      - pg_files:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8000:8000"
    networks:
      - web
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

volumes:
  pg_files:

networks:
  web:
    driver: bridge
