version: "3.8"
services:
  db:
    image: postgres:14-alpine
    networks:
      - web
    env_file:
      - .env

  web:
    build:
      context: .
    ports:
      - "8000:8000"
    networks:
      - web
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db

networks:
  web:
    driver: bridge
