# Generated by Django 4.2.9 on 2024-01-26 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0003_alter_wallet_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="txid",
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
